sudo: required
dist: trusty
language: node_js

node_js:
- '6.9.1'
- 'stable'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - google-chrome-stable
    - g++-4.8
  firefox: 'latest-esr'

cache:
  directories:
    - node_modules

env:
  matrix:
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-default
  global:
    - CXX=g++-4.8
    - secure: Ws3qXGyj8zHDQ83r4XxTq9bZGoY4r0ypuzZ2W/lHGjwQpkEwut79z5MTZd8BlYS/UWxruG04FyiftJmO9Sw9q3G/VAyxbXiLfeRF34bmh0Ymr4iNz/TYiRjw69S/0kuT1W0zV5sxB3JiE37O3T1bHyqZ/H9kMSUA0NGuGkZxoovM8bDCBBnYOnvOQAW70YEWccQO3w/mUmRX+OhUMblsR/y3uIBhmUn7wdCqOdT9PFZM68DWma6DhgcgRbtGjShJ0+jogeEVbb6mqeaPL5l/0sgBHSNY3SEOOKC6Hqo5FyhTvPayzqBtB5xDPehIgHmrJibs925Y6zlIWJHVFu4JjVNGOyf8GKEVN8yFxT5Nyma2hV5JAErCYIKttKiN298aJdkLw/VaHEdkgi2f+RY7Mrjj7eqD7nsdZ6LdMbVqqlDfzX7pKTktJwVxUkQy8WmdufG/LHgK4C6RVdcG7hPkr3IytCpsUMNIEnpOfBbrXG56ENK4akF39AmbagQWr4hExIWsKaYihH9VNnShunsBoAuSuLZaZPQi/VPvmM7J5U0Acaql33A8Rxy/iZ5x2SvqCYO/t2mKj5x72yYhUO/3YY/H5FcughRYUn0rQYvdiCU55JXJBbm0iGEWbRT8y38gaXwai058SeHhZPMe6lxsG6OZMXFuWRqZCFLF7+iNCrs=

matrix:
  fast_finish: true
  allow_failures:
  - node_js: 'stable'

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- npm config set spin false
- npm install -g coveralls pr-bumper

install:
- $(npm root -g)/pr-bumper/.travis/maybe-install.sh

script:
- $(npm root -g)/pr-bumper/.travis/maybe-test.sh
- if [ $EMBER_TRY_SCENARIO == "default" ]; then $(npm root -g)/pr-bumper/.travis/maybe-bump-version.sh; fi

after_success:
- $(npm root -g)/pr-bumper/.travis/maybe-publish-coverage.sh

deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: CUE3NS6dH9snRSvOZjxR9zUT4u5CsxzafCpIVyCboub5fTaxm58YMnbFAjBIYAmU2HTrHIIhHCrPPNyHdlOcLCdpYdJ2AFP2tvLjMAso6p0M15Cic4Sh01u2sQIfdFWBN82ucqlx13Mx7+JEbewuoswdcgMBOEyD3UbQ9Uo6j9YzYym19AY9+ndqcV9TD3Jp1yxBcQPo53poADHqMPFt2xQKVMdSbAua5zz8fPMPsPmvgUrdhVx0J9Ly2uF8Rdhp3L73gspG66GA/MZqd0264mr7lcq3LxW7EtIAJaVFLsYNYjYNBAjai1/jtDoA1paRh+lClD/X2waSEIECgZhm8mOzqcLGRNvzwXQTz7J2I8wh2tKEfEQmnUQxMlwIy2yWakFBjbxG3/0lwXKE1OTadcjjA+J0WUDjsWumuSq8jXIFNupUo++Jx6K2lchbGCTLoMGFhaRpoGdwItjvnIape2ivnqTXNbFiN0ysf+fAcaS33YdHNNrYEhGEy1DskHj1uC1Xz7Y5gdhYTfqXgkASyFlESOVNSPQh5L0zQp9la02fkx2LfDhYryrnFrkYbTU3O0jX9MrLBIXRdCG/ErkOjIFwMJL8aiO0hiy1jIgCB+R01BOTrb2VQf17yYV+rKZ+/Db6beJqB3KzhjaydOO05OxOb+bv9qwAxXdWJ9+PO0Y=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'ember-default'"
    node: 'stable'
    tags: true

after_deploy:
- .travis/publish-gh-pages.sh

notifications:
  slack:
    secure: CwDE8uVpvVPyIQFSZzYvUJ6ev1+QGSEkIZwbY0JpnusYGKlehLJbTSY6SzkNC9/Be/6HBsAyT7HycMNPWa9CJiXCqQzKoRtY1QIzuQgcjRL4O5VsXYMj/4ctPfCauXzX3GrfF6PRXLDG2ZeWed84u4YMjR7Zrl/kgVOZhL8y3xPET4/6zX/CIVhHDrvUng5c9xutj2i0gRkKuxOc8NM484d5TFy2qio7jrUobuVO2BNJvH1EcGJi35HszOcXaXr6pdng5Q3kXheOHrkjwxig0pmhKFxEHFeuVLvrfzSOiTNvJg7RvVpbTcFkl9dGmu4UuQOIykcP31ewmgaqayO52z/eKVAGzAteNlSkQFzvpmPtEaG0xY3XgK88zRsNLEix+xuDIYkokXqBq0GUpr5wCbOhfIJM17tphsTFjH9KLay/GcY7cu3Fp2EeYHCr4ui8GmtF+LGTbvYbYVTsOegKuOO/mWtmaEW80YtWVjgZEAFT3wr5pKN5HSt1J+Ghh3wSP0thg1U1IfMPstluireH+d8WhmJw9X+ayfgNl9/WXHfyZP1YA9vehz0BJMLX3SxtWY2LnoEe9RE6K/0AET/fFUkk8ZpTYcOF5PVacjytKXnUO4p21x7l8MznBgHuWjLVSDK+4oPv87Ef2p+XGaduLFSPD205J6DtnwQtWXkHsuw=
